version: '3.8'

services:

  nginx:
    image:   junwon1131/s10c102-nginx:latest
    container_name: nginx-https
    build:
      context: nginx
      dockerfile: Dockerfile

    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/j10c102.p.ssafy.io/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/j10c102.p.ssafy.io/privkey.pem:/etc/ssl/private/privkey.pem
    restart: unless-stopped
    depends_on:
      - back

      
  back:
    container_name: back
    image: junwon1131/s10c102-back:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - jenkins-network
#    environment:
#      - USE_PROFILE=dev
#      - SPRING_PROFILES_ACTIVE=prod

networks:
  jenkins-network:
    external: true
