version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: fullerting
      MYSQL_PASSWORD: ssafy
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 3

  mongodb:
    image: mongo:6.0  # ← 공식 이미지로 변경
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db  # 공식 이미지의 기본 경로
    environment:
      MONGO_INITDB_DATABASE: fullerting
    restart: always


volumes:
  mysql_data:
  mongodb_data:
