version: '3.8'

services:
  mongodb-test:
    image: mongo:6.0
    container_name: mongodb-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: test_fullerting
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - test-network

  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - test-network

  kafka-test:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-test
    ports:
      - "9094:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-test:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-test:9092,CONTROLLER://kafka-test:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    volumes:
      - kafka_test_data:/var/lib/kafka/data
    networks:
      - test-network

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-init
    depends_on:
      - kafka-test
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...'
        cub kafka-ready -b kafka-test:9092 1 30
        echo 'Creating test topics...'
        kafka-topics --create --if-not-exists --bootstrap-server kafka-test:9092 --topic bid_requests --partitions 3 --replication-factor 1
        kafka-topics --create --if-not-exists --bootstrap-server kafka-test:9092 --topic kafka-alarm --partitions 3 --replication-factor 1
        echo 'Topics created successfully!'
        kafka-topics --list --bootstrap-server kafka-test:9092
      "
    networks:
      - test-network

volumes:
  mongodb_test_data:
  redis_test_data:
  kafka_test_data:

networks:
  test-network:
    driver: bridge