version: '3.8'

services:
  # MongoDB for testing
  mongodb-test:
    image: mongo:6.0
    container_name: mongodb-test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_DATABASE: test_fullerting
    volumes:
      - mongodb_test_data:/data/db
    networks:
      - test-network

  # Redis for testing
  redis-test:
    image: redis:7-alpine
    container_name: redis-test
    ports:
      - "6380:6379"
    volumes:
      - redis_test_data:/data
    networks:
      - test-network

  # Kafka for testing
  zookeeper-test:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper-test
    ports:
      - "2182:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - test-network

  kafka-test:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-test
    depends_on:
      - zookeeper-test
    ports:
      - "9094:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-test:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - test-network

volumes:
  mongodb_test_data:
  redis_test_data:

networks:
  test-network:
    driver: bridge
