apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv-0
  labels:
    type: local
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/data/kafka"

