apiVersion: apps/v1
kind: Deployment
metadata:
  name: fullerting-backend-deployment
  labels:
    app: fullerting-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fullerting-backend
  template:
    metadata:
      labels:
        app: fullerting-backend
    spec:
      containers:
        - name: fullerting-backend
          image: your-repo/fullerting-backend:latest # Replace with your actual image
          ports:
            - containerPort: 8080 # Or your application's port
          env:
            # Existing database configuration
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/fullerting?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: mysql-secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-secret
            # ? Correct Redis connection details
            - name: SPRING_REDIS_HOST
              value: redis-service
            - name: SPRING_REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1024Mi"
