spring:
  datasource:
    url: jdbc:mysql://localhost:3305/fullerting
    username: root
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver


    #####
    mongodb:
      image: mongo:latest
      container_name: mongodb_boot
      restart: always
      ports:
        - 27017:27017
      volumes:
        - /home/ubun2/mongodb/data:/data
      environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=ssafy

  data:
    redis:
      host: localhost
      port: 6378

  security:
    user:
      name: test
      password: 1234

  jwt:
    access: whatwehavetowantinalifeismentalsatisfactionnotmaterialone
    refresh: youforgetthisyoualwaysfeelfailevenifyouwillgeteverything
    accesstime: 432000000
    refreshtime: 604800000 # 7Days

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 110MB

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create

cloud:
  aws:
    credentials:
      access-key: AKIAW3MEAWFWGVMIB3VX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: fullerting-s3-v2
      stack:
        auto: false

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html

logging:
  level:
    org:
      springframework:
        security:
          web:
          FilterChainProxy: DEBUG
      hibernate:
        SQL: DEBUG                             # SQL 쿼리 로그 출력
        type:
          descriptor:
            sql:
              BasicBinder: TRACE              # 바인딩 된 파라미터 값 로그
    root: INFO
    com.ssafy.fullerting: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"

server:
  port: 8082
  servlet:
    context-path: /
  websocket:
    port: 8181
